name: CI Pipeline

on: [push, pull_request]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 20.x
    - name: Install Dependencies
      run: npm install
    - name: Audit
      run: npm audit
    - name: Lint
      run: npm run lint
